### ISSUE TITLE
Addon doesn't work after some hours/days

### ISSUE THREAD

**Issue by N1co93** [thiagobruch/HA_Addons#15]
Hello,

sadly the addon seems to stop working after some hours/days. The addon is still running, but the newest items on the Amazon shopping list aren't detected/imported to Home Assistant
After I restart the addon everything works fine for hours/days.

What information do you need to have a deeper look into this issue?

Thank you in advance.

**Comment by thiagobruch** [comment]
Hi @N1c093 ,

I also experience the same thing on mine and tried several things to fix it.
I believe it may be something related to the cookies saved in the headless browser running in the Add-On.

The easiest thing for me was to create a Automation in HA to restart the Add-on every 5th minute of hour.

```
alias: Add-on Alexa Restart
description: ""
triggers:
  - trigger: time_pattern
    minutes: "5"
conditions: []
actions:
  - action: hassio.addon_restart
    metadata: {}
    data:
      addon: 1fd84202_alexa_shopping_list_scraper
mode: single
```
