### ISSUE TITLE
NOT AN ISSUE : Automation to add/delete item on Amazon via HA with voice command

### ISSUE THREAD

**Issue by tomredhot** [thiagobruch/HA_Addons#18]
Hi!

First of all : thanks for all this work! The solution you found when amazon cut its API is a very good hack. Not perfect, but really good.

Then, and to give a little help at my level, I wanted to share with you and the other users a little tip based on your example of deleting the shopping list on Amazon at midnight.
Indeed, for those who want to keep their shopping list on Amazon (and the Alexa application), without deleting it, I propose the following automations:

When an item is added via HA, tell Alexa to add this item to the shopping list on Amazon: 

```
alias: ADD ITEM ON AMAZON
description: ""
triggers:
  - trigger: event
    event_type: shopping_list_updated
    event_data:
      action: add
conditions: []
actions:
  - data:
      media_content_type: custom
      media_content_id: add "{{ trigger.event.data.item.name }}" on my shopping list
      enqueue: play
    enabled: true
    action: media_player.play_media
    target:
      entity_id: media_player.my_echo
mode: single
```

When an item is marked as completed (purchased) via HA, tell Alexa to delete this item from the purchase list on Amazon:
```
alias: DELETE ITEM ON AMAZON
description: ""
triggers:
  - trigger: event
    event_type: shopping_list_updated
    event_data:
      action: update
conditions:
  - condition: template
    value_template: "{{ trigger.event.data.item.complete }}"
actions:
  - data:
      media_content_type: custom
      media_content_id: delete "{{ trigger.event.data.item.name }}" on my shopping list
      enqueue: play
    enabled: true
    action: media_player.play_media
    target:
      entity_id: media_player.my_echo
mode: single
```

This 2 automations uses the same method as your example on the readme... so... thanks you for the idea! (I removed the volume reduction, it doesn't bother me that Alexa speaks when I add/check an item).
The second one doesn't work every time. Especially when the item checked has an inconsistent or overly complicated name.

Again, thank you!

**Comment by tomredhot** [comment]
Oh, and I forgot something.
Because of my automation to add an item via TTS on Alexa, and the way Alexa "writes" this item, your blueprint, when it parses Amazon, triggers sometime a "shopping_list_updated" event for an item already in the shopping list (because of punctuation, capital letters, and accents,  etc..., the blueprint determines badly that an item already exists).
This re-launch my automation to add an item via TTS, for the same item...

So I modified your blueprint to deactivate my automation for a few seconds when you add the items to the HA shopping list.

```
blueprint:
  name: Import Alexa shoppinglist
  description: Import Alexa shopping to your Home Assistant shopping list.
  domain: automation
  author: N1c093
  input:
    webhook_trigger:
      name: Webhook Trigger
      description: Please create a webhook trigger. Other triggers are not supported!
      selector:
        trigger: {}
    shopping_list:
      name: Shopping List
      description: Which shopping list should receive the entries from the Alexa shopping
        list?
      selector:
        entity:
          filter:
          - domain:
            - todo
          multiple: false
    automation_to_stop:
      name: Automation to stop when import new items
      description: To avoid triggering the automation of adding items to the Amazon shopping list via TTS hack , we deactivate it for 5 seconds.
      selector:
         entity:
          filter:
          - domain:
            - automation
  source_url: https://github.com/thiagobruch/HA_Addons/blob/main/alexa_shopping_list_scraper/Blueprint_Import-Alexa-Shoppinglist.yaml
mode: parallel
max: 100
variables:
    shopping_list: !input shopping_list
    automation_to_stop: !input automation_to_stop    
    
trigger: !input webhook_trigger
action:
  - service: automation.turn_off
    target:
      entity_id: !input automation_to_stop

  - delay: "00:00:02"  # # Small delay to ensure automation is disabled

  - data: {}
    response_variable: list
    entity_id: !input shopping_list
    action: todo.get_items

  - if:
      - condition: template
        value_template: '{{ trigger.json.name not in list[shopping_list]["items"] | map(attribute="summary") | list }}'
    then:
      - entity_id: !input shopping_list
        data:
          item: '{{ trigger.json.name }}'
        action: todo.add_item

  - delay: "00:00:03"  # Wait 3 seconds before reactivating the automation

  - service: automation.turn_on
    target:
      entity_id: !input automation_to_stop

```

This is all a bit of a hack, but I think there is some good logic to come out of it, and perhaps some new features to add to the blueprint.
