### ISSUE TITLE
Addon does not call the webhook

### ISSUE THREAD

**Issue by stefangries** [thiagobruch/HA_Addons#3]
First of all, thank you for doing the work to create this addon.

Unfortunately, I have a problem with the addon. After I have made the configuration, my webhook is not called. I only receive a log output and every 5 minutes an SMS from Amazon with an OTP.

Log:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

My Config:
```
Amazon Login: My Mail
Amazon Pass: My Pass
Amazon Secret: 4TNCUPR.........A
HA Webhook URL: https://mydomain.de/api/webhook/-hRvqwLAV......p0s-
Amazon Sign In URL: https://www.amazon.de/ap/signin?openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.amazon.de%2F%3Fref_%3Dnav_signin&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=deflex&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
Amazon Shopping List Page: https://www.amazon.de/alexaquantum/sp/alexaShoppingList?ref_=list_d_wl_ys_list_1
```

I have already tried to set the log level to debug, but the log output does not change. Anyone have any ideas what else I can try, or is there possibly a bug?

**Comment by thiagobruch** [comment]
Hi @stefangries,

The issue with the SMS is that you Amazon account is configured to use SMS as the primary mode for the 2FA.

1 - Login to Amazon https://www.amazon.com/
2 - Go to Your Account => Login & Security and click on "Manage" under 2-step verification
3 - Remove the 2-step Authentication and add again using the App as the first option.
To do this, tap or click “Disable,” then check the box next to “Also clear two-step verification settings” in the window that appears. Finally, re-enable two-step verification using your authenticator app as your preferred method.
4 - Under Authenticator App, click on Add New App
5 - Click on "Can't scan the barcode" and save the Key (13 sets of 4 characters each)
6 - Remove the spaces of the Key (you will have something like this "ASDMASDFMSKDMKSFMKLASDDADABB6JNRNF7WFEHQW23H238R7843")

This should prevent the Amazon to send SMS every 3 minutes to authenticate.

**Comment by stefangries** [comment]
Hi @thiagobruch,

Thank you for your message. I have now set up the MFA again. Since then, the SMS no longer appears, but the other behavior is unchanged. The automation with the webhook is still not called.

**Comment by thiagobruch** [comment]
Hi @stefangries ,

I have changed the Beta version and added a return on the log to the items in the list to check if the program is getting there.
Please uninstall the main addon and install the Beta version.
Run the Beta version and check the logs for the list of items in the Shopping List. If the items are being displayed in the log, the program is able to read them.

In addition, please configm that during the MFA Process, after you added the APP and grabbed the Key, you also scanned the QR Code with an Authenticator App (i.e.  [Google Authenticator](https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2) ) and confirmed with the 6 digits number from the app.
[

**Comment by stefangries** [comment]
Thank you for your time and efforts to make this work. With your help I was able to locate the error: 

It seems like it is necessary to call the internal HA webhook URL (http://homeassistant.local:8123/...) and not a public one (https://ha.myurl.com/...). Maybe this should be mentioned. Another option would to be just ask for the webook id instead of the URL.

Additionally, I would recommend to provide a complete automation yaml instead of steps on how to reproduce it. Moreover, I had to make changes to your code to make it work, for example replacing `action: shopping_list.add_item` with `action: todo.add_item` and to add my own entity id of the todo list. If you like to use it, here is a complete working yaml of an automation:

```
alias: Einkaufsliste
description: ""
trigger:
  - platform: webhook
    allowed_methods:
      - POST
      - PUT
      - GET
      - HEAD
    local_only: false
    webhook_id: "-7yZPnpiqhjvHFkgX8vpRGrnA-"
condition: []
action:
  - action: todo.get_items
    data:
      status:
        - needs_action
        - completed
    response_variable: todo
    target:
      entity_id: todo.einkaufsliste
  - if:
      - condition: template
        value_template: |-
          {{trigger.json.name not in todo['todo.einkaufsliste']['items'] |
                    map(attribute='summary') | list}}
    then:
      - data_template:
          item: "{{ trigger.json.name }}"
        target:
          entity_id: todo.einkaufsliste
        action: todo.add_item
mode: parallel
max: 100
```
